### ISSUE TITLE
Restore original column classes in sp methods

### ISSUE THREAD

**Issue by ateucher** [ateucher/rmapshaper#46]
In conversion of geojson to sp (`GeoJSON_to_sp`), should ensure `StringsAsFactors = FALSE` in `rgdal::readOGR`

**Comment by mdsumner** [comment]
+1

Just got burnt by this ;)  I wonder if this is a clear case where the class of each attribute should be stored prior to the write/read steps? It's pretty annoying, since you can't specify  colClasses in readOGR, but you might record what attributes were what, and restore the factors (and their levels) as required.

**Comment by ateucher** [comment]
Yes, great idea. Thanks!

**Comment by ateucher** [comment]
Changed issue title to reflect this

**Comment by ateucher** [comment]
Started in col-classes branch
