### ISSUE TITLE
Issue with ms_simplify and sys = TRUE

### ISSUE THREAD

**Issue by maka1234** [ateucher/rmapshaper#87]
Hey!

I read through the documentation and tried to run ms_simplify using sys = TRUE
`library(sf)` 
`library(tmap)` 
`library(rmapshaper)`  
`fiss <- read_sf("/path/to/file")`
`fiss <- ms_simplify(fiss, keep = 0.02, sys = TRUE) `

This returns the following error:
[i] Error: File not found (C:/Users/User)
Run mapshaper -h to view help
Cannot open data source C:\Users\User\AppData\Local\Temp\RtmpMD75li\file230064ff2da8.geojson
Error in CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  : 
  Open failed.

I've installed node.js:
`check_sys_mapshaper()`
mapshaper version 0.4.120 is installed and on your PATH

Any idea what I'm doing wrong? I'm having a really hard time opening large shapefiles without this.

**Comment by ateucher** [comment]
This is an odd one. Can you check to see if the file was successfully written to that location? (`C:\Users\User\AppData\Local\Temp\RtmpMD75li\file230064ff2da8.geojson`)

**Comment by ateucher** [comment]
I wonder if there's a space or a special character in your username (I'm guessing in this report you substituted "User" for your actual user name)?

**Comment by geospatial-dave** [comment]
Hey mate, I've encountered a similar issue as maka above, following up on your questions:
- File was not successfully written to location
- My user is david, definitely no special characters there

If I can help in any other way let me know, I'm trying to simplify 150MB .shp file and need to use the sys=TRUE function as it just hangs forever otherwise.

Error below:


Error: [each] Command expects a single value. Received: 'rmapshaperid = this.id'
Run mapshaper -h to view help
Cannot open data source C:\Users\david\AppData\Local\Temp\RtmpOybJjr\file281467f33312.geojson
Error in CPL_read_ogr(dsn, layer, as.character(options), quiet, type,  : 
  Open failed.
In addition: Warning message:
running command 'mapshaper C:/Users/david/AppData/Local/Temp/RtmpOybJjr/file2814188f2e0f.geojson snap -simplify 0.111  weighting=0.7 keep-shapes -each 'rmapshaperid = this.id' -o C:\Users\david\AppData\Local\Temp\RtmpOybJjr\file281467f33312.geojson' had status 1

**Comment by ateucher** [comment]
Closing (See #77), should be fixed in v0.4.1. Please reopen if this is still happening and you have the latest `rmapshaper` from CRAN (0.4.1)
